- name: Remove Container
  docker_container: 
    name: "{{ container_name }}"
    state: stopped

- name: Remove Container
  docker_container: 
    name: "{{ container_name }}"
    state: absent

- name: Run Application
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}"
    state: started
    restart: yes
    ports:
        - "80:8080"

